### ISSUE TITLE
NumPy versioning issues

### ISSUE THREAD

**Issue by BrendanMesters** [rubenIng93/mmwave-decoder#4]
It seems that Pandas is expecting a version of NumPy < 2.0.0
If the newest version of numpy is used you get the following error:
```
Traceback (most recent call last):
  File "/home/brendan/Documents/Uni/Thesis/mmwave-decoder/decode_dat.py", line 4, in <module>
    import pandas as pd
  File "/home/brendan/Documents/Uni/Thesis/mmwave-decoder/decoder_venv/lib/python3.10/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/brendan/Documents/Uni/Thesis/mmwave-decoder/decoder_venv/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/home/brendan/Documents/Uni/Thesis/mmwave-decoder/decoder_venv/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

This can be solved by adding numpy as a version pinned requirement, so in `requirements.txt` you should add:
`numpy==1.26.4`, this should solve the issue.

**Comment by BrendanMesters** [comment]
This might also be solvable by requering a newer version of Pandas, but I haven't tried that, I at least know that down-pinning numpy for sure works
